info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple example of a Gin API with Swagger documentation.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Gin API Example
  version: "1.0"
paths:
  /hello:
    get:
      description: Returns a simple hello world message
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Say hello
      tags:
      - hello
swagger: "2.0"
